export const design = {
  padding: {
    xs: "p-2",
    sm: "p-4",
    md: "p-6",
    lg: "p-8",
    xl: "p-12",
    section: "py-12 px-4 sm:px-6 lg:px-8",
    cell: "p-5",
    badge: "px-3 py-1",
    button: "px-8 py-4",
    buttonSm: "px-6 py-3",
    x10: "px-10",
  },
  margin: {
    sm: "m-4",
    md: "m-6",
    lg: "m-8",
  },
  gap: {
    xs: "gap-2",
    sm: "gap-4",
    md: "gap-6",
    lg: "gap-8",
  },
  space: {
    section: "space-y-16",
    sectionLg: "space-y-20",
  },
  borderRadius: {
    sm: "rounded-sm",
    md: "rounded-md",
    lg: "rounded-lg",
    xl: "rounded-xl",
    "2xl": "rounded-2xl",
    "3xl": "rounded-3xl",
    full: "rounded-full",
  },
  shadow: {
    sm: "shadow-sm",
    md: "shadow-md",
    lg: "shadow-lg",
    xl: "shadow-xl",
    "2xl": "shadow-2xl",
  },
  typography: {
    h1: "text-4xl sm:text-5xl font-bold tracking-tight",
    h2: "text-3xl font-bold",
    h3: "text-2xl font-bold",
    h4: "text-xl font-bold",
    body: "text-base",
    bodyLg: "text-lg",
    caption: "text-sm",
    small: "text-xs",
    label: "text-sm font-bold uppercase tracking-wider",
    nav: "text-lg font-medium",
  },
  size: {
    imageCard: "h-48",
    imageBanner: "h-[400px]",
    dividerH: "h-1",
    dividerW: "w-16",
    thumb: "w-10 h-10",
    icon: "w-7 h-7",
    iconSm: "w-5 h-5",
    iconMd: "w-6 h-6",
  },
  maxWidth: {
    prose: "max-w-2xl",
    page: "max-w-7xl",
    detail: "max-w-6xl",
  },
};
